/* ═══ data.js — ฐานข้อมูลสเปคจำลอง (mock)
   ของจริง: ย้ายเข้า Supabase ตาราง cpus/gpus/... แล้วให้ backend เป็นคนเลือก
   ทุกชิ้นมี dims (มม.) เพื่อวาดผัง 2D — ตรงกับ D9 ใน Obsidian ═══ */

window.SPEC_DATA = (function () {

  const FX = 36;        // บาท/ดอลลาร์ (ค่าประมาณ ส.ค. 2026)
  const ELEC = 4.5;     // บาท/หน่วยไฟ (kWh)

  function buyLinks(name) {
    const q = encodeURIComponent(name);
    return [
      { shop: "JIB",    url: "https://www.jib.co.th/web/product/product_search/0?str_search=" + q },
      { shop: "Advice", url: "https://www.advice.co.th/search?keyword=" + q },
      { shop: "BNN",    url: "https://www.bnn.in.th/th/p?q=" + q },
    ];
  }

  /* part = { type, name, price, reason, upgrade?, dims:{w,h}? } — dims หน่วย มม. (มุมมองข้างเคส) */

  const AI_TIERS = [
    {
      id: "ai1", min: 25000, max: 44999,
      name: "เครื่องเริ่มต้นสาย Inference (24GB VRAM)",
      chip: "ENTRY · 24GB",
      watt: 420, idleWatt: 65,
      kase: { name: "Mid Tower ATX", w: 465, h: 470 },
      cloud: { rateUsd: 0.34, gpuLabel: "RTX 4090 24GB (RunPod Community)", refreshMonths: 36 },
      parts: [
        { type: "GPU", name: "RTX 3090 24GB (มือสอง)", price: 18500, dims: { w: 313, h: 138 },
          reason: "VRAM 24GB ต่อราคาถูกที่สุดในตลาด รันโมเดล 7-13B แบบเต็มความละเอียดได้",
          upgrade: "RTX 5090 32GB เมื่องบถึง (+70,000)" },
        { type: "CPU", name: "Ryzen 5 7500F", price: 5200, dims: { w: 40, h: 40 },
          reason: "งาน inference คอขวดอยู่ที่ GPU ซีพียู 6 คอร์พอแล้ว เอาเงินไปลง VRAM" },
        { type: "MB", name: "B650M เมนบอร์ด", price: 3900, dims: { w: 244, h: 244 },
          reason: "รองรับ Zen 4/5 อัปเกรดซีพียูได้อีกอย่างน้อยหนึ่งรุ่น" },
      ],
      parts2: [
        { type: "RAM", name: "DDR5 32GB (2×16)", price: 3200, dims: { w: 134, h: 32 },
          reason: "โหลดโมเดลผ่านแรมก่อนเข้า GPU 32GB คือขั้นต่ำที่ไม่อึดอัด", upgrade: "64GB ถ้าจะ offload โมเดลใหญ่ (+3,400)" },
        { type: "SSD", name: "NVMe 1TB Gen4", price: 2400, dims: { w: 80, h: 22 },
          reason: "ไฟล์โมเดลใหญ่ (7B ≈ 8GB, 70B ≈ 40GB) โหลดจาก NVMe เร็วกว่า SATA 6 เท่า" },
        { type: "PSU", name: "850W 80+ Gold", price: 2900, dims: { w: 150, h: 86 },
          reason: "3090 มี transient spike สูง เผื่อหัว 12V ไว้ ไม่งั้นดับกลางเทรน" },
        { type: "COOL", name: "Tower Air Cooler", price: 900, dims: { w: 120, h: 155 },
          reason: "7500F ตัวเย็น ลมพอ เงียบกว่า AIO ถูกกว่า และไม่มีปั๊มให้พัง" },
        { type: "CASE", name: "Mid Tower Airflow", price: 1600, dims: { w: 465, h: 470 },
          reason: "หน้าตะแกรง การ์ดมือสองต้องการลมเลี้ยงดีเป็นพิเศษ" },
      ],
      perf: [
        { k: "Llama 3.1 8B (Q8)", v: "~55 tok/s" },
        { k: "Qwen 14B (Q5)", v: "~28 tok/s" },
        { k: "70B (Q4)", v: "ไม่แนะนำ — VRAM ไม่พอ" },
        { k: "Stable Diffusion XL", v: "~1.6 ภาพ/นาที" },
      ],
      temps: [
        { k: "GPU ขณะ inference", v: "78–84°C", hot: true },
        { k: "CPU โหลดปกติ", v: "60–68°C" },
        { k: "กินไฟเต็มโหลด", v: "~420W" },
        { k: "เสียง", v: "ได้ยินชัดตอนรัน" },
      ],
      upgrades: [
        { title: "แรม → 64GB", cost: "+3,400", gain: "offload โมเดลที่ล้น VRAM ได้จริง" },
        { title: "เพิ่ม RTX 3090 ใบที่สอง", cost: "+18,500", gain: "VRAM รวม 48GB → รัน 70B Q4 ได้" },
        { title: "UPS 1000VA", cost: "+3,200", gain: "ไฟดับระหว่าง fine-tune ไม่เสียงานทั้งคืน" },
      ],
    },
    {
      id: "ai2", min: 45000, max: 99999,
      name: "เครื่อง 48GB VRAM สองใบ — รัน 70B ในบ้าน",
      chip: "DUAL GPU · 48GB",
      watt: 780, idleWatt: 95,
      kase: { name: "Full Tower", w: 560, h: 545 },
      cloud: { rateUsd: 0.68, gpuLabel: "2× RTX 4090 (RunPod Community)", refreshMonths: 36 },
      parts: [
        { type: "GPU", name: "RTX 3090 24GB (มือสอง) ×2", price: 37000, dims: { w: 313, h: 280 },
          reason: "VRAM รวม 48GB คือทางเดียวที่งบนี้จะรัน 70B Q4 ได้ทั้งก้อน ไม่ต้อง offload",
          upgrade: "ขายสองใบไปตัว RTX 5090 32GB เมื่อโมเดลเล็กลงแต่เร็วขึ้นสำคัญกว่า" },
        { type: "CPU", name: "Ryzen 9 7900 (12C)", price: 14500, dims: { w: 40, h: 40 },
          reason: "เตรียมข้อมูล + tokenize ขนานกับ GPU สองตัว 12 คอร์ไม่เป็นคอขวด" },
        { type: "MB", name: "X670E (PCIe x8/x8)", price: 9800, dims: { w: 305, h: 244 },
          reason: "แยกเลน x8/x8 ให้การ์ดสองใบ บอร์ด B-series ทำไม่ได้" },
      ],
      parts2: [
        { type: "RAM", name: "DDR5 64GB (2×32)", price: 6900, dims: { w: 134, h: 32 },
          reason: "โหลด checkpoint 70B (~40GB) เข้าแรมก่อนกระจายลง GPU", upgrade: "128GB สำหรับ dataset ใหญ่ (+7,200)" },
        { type: "SSD", name: "NVMe 2TB Gen4", price: 4500, dims: { w: 80, h: 22 },
          reason: "เก็บโมเดลหลายเวอร์ชัน + dataset โดยไม่ต้องลบสลับ" },
        { type: "PSU", name: "1200W 80+ Platinum", price: 6500, dims: { w: 180, h: 86 },
          reason: "การ์ดสองใบ transient รวมทะลุ 900W ได้ ต้องเผื่อจริงจัง" },
        { type: "COOL", name: "AIO 360mm", price: 4200, dims: { w: 394, h: 55 },
          reason: "ความร้อนสะสมในเคสสูงมากจากการ์ดสองใบ ต้องรีดออกไว" },
        { type: "CASE", name: "Full Tower (ช่องว่างระหว่างการ์ด)", price: 3900, dims: { w: 560, h: 545 },
          reason: "การ์ดใบบนจะดูดลมร้อนใบล่าง ต้องมีระยะห่างอย่างน้อย 2 สล็อต" },
      ],
      perf: [
        { k: "Llama 3.1 70B (Q4)", v: "~16 tok/s" },
        { k: "Llama 3.1 8B (Q8)", v: "~100 tok/s" },
        { k: "LoRA fine-tune 8B", v: "ทำได้สบาย" },
        { k: "ผู้ใช้พร้อมกัน (8B)", v: "~4-6 คน" },
      ],
      temps: [
        { k: "GPU บน / ล่าง", v: "84 / 76°C", hot: true },
        { k: "CPU", v: "70–78°C" },
        { k: "กินไฟเต็มโหลด", v: "~780W", hot: true },
        { k: "ค่าไฟถ้ารันทั้งวัน", v: "~2,500฿/ด." },
      ],
      upgrades: [
        { title: "NVLink Bridge (ถ้าหาได้)", cost: "+4,000", gain: "แชร์ VRAM ระหว่างใบเร็วขึ้นตอนเทรน" },
        { title: "2.5GbE/10GbE NIC", cost: "+1,900", gain: "เสิร์ฟโมเดลให้ทีมผ่าน LAN ไม่หน่วง" },
        { title: "แยกวงจรไฟ + UPS", cost: "+6,000", gain: "780W ต่อเนื่อง เบรกเกอร์บ้านทั่วไปเริ่มตึง" },
      ],
    },
    {
      id: "ai3", min: 100000, max: 300000,
      name: "RTX 5090 Workstation — แรงสุดในร่างเดียว",
      chip: "PRO · 32GB GDDR7",
      watt: 850, idleWatt: 90,
      kase: { name: "Full Tower E-ATX", w: 560, h: 560 },
      cloud: { rateUsd: 0.99, gpuLabel: "RTX 5090 32GB (RunPod Secure)", refreshMonths: 36 },
      parts: [
        { type: "GPU", name: "RTX 5090 32GB", price: 89000, dims: { w: 340, h: 150 },
          reason: "แบนด์วิดท์ 1.8TB/s + FP4 — inference เร็วกว่า 3090 ราว 3 เท่าในวัตต์ใกล้กัน",
          upgrade: "ใบที่สองเมื่อขยับไปเทรนจริงจัง (+89,000)" },
        { type: "CPU", name: "Ryzen 9 9950X (16C)", price: 23000, dims: { w: 40, h: 40 },
          reason: "งาน preprocess/บีบอัด dataset ระดับนี้กิน CPU จริง 16 คอร์คุ้ม" },
        { type: "MB", name: "X870E", price: 13500, dims: { w: 305, h: 244 },
          reason: "PCIe 5.0 เต็มเลนให้ทั้ง GPU และ NVMe" },
      ],
      parts2: [
        { type: "RAM", name: "DDR5 96GB (2×48)", price: 11500, dims: { w: 134, h: 32 },
          reason: "เผื่อ KV cache + dataset ในแรม ไม่ swap ระหว่างเทรน" },
        { type: "SSD", name: "NVMe 4TB Gen5", price: 8900, dims: { w: 80, h: 22 },
          reason: "checkpoint ระหว่างเทรนเขียนหนักมาก Gen5 ลดเวลารอเป็นนาทีต่อรอบ" },
        { type: "PSU", name: "1300W ATX 3.1", price: 7900, dims: { w: 200, h: 86 },
          reason: "หัว 12V-2x6 native สำหรับ 5090 ไม่ต้องใช้สายแปลง (จุดไหม้อันดับหนึ่ง)" },
        { type: "COOL", name: "AIO 420mm", price: 5500, dims: { w: 458, h: 55 },
          reason: "9950X บูสต์ยาวได้เมื่อเย็นพอ งานเทรนคือโหลดต่อเนื่องหลายชั่วโมง" },
        { type: "CASE", name: "Full Tower E-ATX", price: 4500, dims: { w: 560, h: 560 },
          reason: "การ์ดยาว 340มม. + หม้อน้ำ 420มม. เคสธรรมดาใส่ไม่ลง" },
      ],
      perf: [
        { k: "Llama 3.1 8B (FP8)", v: "~140 tok/s" },
        { k: "Qwen 32B (Q4)", v: "~35 tok/s" },
        { k: "LoRA fine-tune 8B", v: "~45 นาที/epoch" },
        { k: "SDXL", v: "~7 ภาพ/นาที" },
      ],
      temps: [
        { k: "GPU เต็มโหลด", v: "72–78°C" },
        { k: "CPU เต็มโหลด", v: "80–88°C", hot: true },
        { k: "กินไฟเต็มโหลด", v: "~850W", hot: true },
        { k: "ค่าไฟ 8 ชม./วัน", v: "~920฿/ด." },
      ],
      upgrades: [
        { title: "10GbE + NAS แยก", cost: "+15,000", gain: "แยก dataset ออกจากเครื่องเทรน ทีมเข้าถึงได้" },
        { title: "RTX 5090 ใบที่สอง", cost: "+89,000", gain: "VRAM 64GB — fine-tune 70B ด้วย QLoRA" },
      ],
    },
  ];

  const HOME_TIERS = [
    {
      id: "h1", min: 5000, max: 11999,
      name: "Mini PC N100 — เซิร์ฟเวอร์เงียบกินไฟ 15W",
      chip: "MINI · 15W",
      watt: 15, idleWatt: 7,
      kase: { name: "Mini PC", w: 130, h: 52 },
      cloud: { rateUsd: 9.99, gpuLabel: "Google One 2TB", refreshMonths: 60, isStorage: true },
      parts: [
        { type: "PC", name: "Mini PC Intel N100 16GB", price: 5900, dims: { w: 115, h: 42 },
          reason: "QuickSync ถอดรหัสวิดีโอ 4K ได้ในตัว กินไฟเท่าหลอดไฟหนึ่งดวง เปิดทั้งปีค่าไฟ ~590฿",
          upgrade: "ขยับไป NAS 4-Bay เมื่อข้อมูลเกิน 4TB" },
        { type: "SSD", name: "SSD 2TB SATA", price: 3800, dims: { w: 100, h: 9 },
          reason: "เงียบสนิท ไม่มีเสียงจานหมุนในห้องนอน — พอสำหรับ media เริ่มต้น" },
      ],
      parts2: [
        { type: "OS", name: "Proxmox / CasaOS (ฟรี)", price: 0, dims: null,
          reason: "รัน Jellyfin + Pi-hole + Immich พร้อมกันได้บน 16GB" },
      ],
      perf: [
        { k: "สตรีม Jellyfin 4K", v: "1–2 จอพร้อมกัน" },
        { k: "Pi-hole / AdGuard", v: "ทั้งบ้านสบาย" },
        { k: "Immich (แทน Google Photos)", v: "ได้ แต่สแกนช้า" },
      ],
      temps: [
        { k: "ตัวเครื่อง", v: "45–60°C" },
        { k: "เสียง", v: "แทบไม่ได้ยิน" },
        { k: "ค่าไฟเปิด 24 ชม.", v: "~49฿/ด." },
      ],
      upgrades: [
        { title: "SSD ภายนอก 4TB", cost: "+4,900", gain: "พื้นที่ backup แยกออกจากตัวเครื่อง" },
        { title: "UPS เล็ก", cost: "+2,200", gain: "ไฟกระชากไม่พังเครื่องที่เปิดตลอด" },
      ],
    },
    {
      id: "h2", min: 12000, max: 34999,
      name: "NAS DIY 4-Bay — เก็บได้ 16TB ขยายได้อีก",
      chip: "NAS · 4-BAY",
      watt: 55, idleWatt: 28,
      kase: { name: "Jonsbo N3 (NAS)", w: 233, h: 262 },
      cloud: { rateUsd: 39.96, gpuLabel: "Google One 2TB ×4 (เทียบความจุ 8TB)", refreshMonths: 60, isStorage: true },
      parts: [
        { type: "CPU", name: "Intel i3-12100", price: 3300, dims: { w: 38, h: 38 },
          reason: "iGPU UHD730 ถอดรหัสวิดีโอให้ Plex/Jellyfin ฟรี ไม่ต้องมีการ์ดจอ" },
        { type: "MB", name: "H610M (6 SATA)", price: 2200, dims: { w: 226, h: 180 },
          reason: "พอร์ต SATA เยอะคือหัวใจของ NAS ประหยัดการ์ดต่อขยาย" },
        { type: "HDD", name: "HDD NAS 8TB ×2 (RAID1)", price: 10800, dims: { w: 147, h: 52 },
          reason: "กระจกเงากันจานพังหนึ่งลูก — RAID ไม่ใช่ backup แต่ซื้อเวลาให้กู้ทัน",
          upgrade: "เพิ่มอีก 2 ลูกเป็น RAIDZ/RAID5 ได้ 16-24TB" },
      ],
      parts2: [
        { type: "RAM", name: "DDR4 16GB", price: 1300, dims: { w: 134, h: 32 },
          reason: "ZFS ชอบแรม 16GB คือจุดเริ่มที่ไม่ต้องกลับมาแก้" },
        { type: "SSD", name: "NVMe 500GB (บูต+แคช)", price: 1300, dims: { w: 80, h: 22 },
          reason: "แยกระบบออกจากจานข้อมูล เปลี่ยน OS ได้โดยไม่แตะไฟล์" },
        { type: "PSU", name: "SFX 450W Bronze", price: 2200, dims: { w: 125, h: 64 },
          reason: "เคส NAS ใช้ PSU เล็ก ประสิทธิภาพช่วงโหลดต่ำสำคัญเพราะเปิด 24 ชม." },
        { type: "CASE", name: "Jonsbo N3 4-Bay", price: 3500, dims: { w: 233, h: 262 },
          reason: "ถาดจานถอดหน้าได้ เปลี่ยนจานไม่ต้องรื้อเครื่อง" },
      ],
      perf: [
        { k: "อ่าน/เขียนผ่าน LAN", v: "~110 MB/s (1GbE)" },
        { k: "สตรีม 4K พร้อมกัน", v: "3–4 จอ" },
        { k: "ความจุใช้จริง (RAID1)", v: "8TB" },
      ],
      temps: [
        { k: "HDD", v: "38–44°C" },
        { k: "CPU", v: "45–55°C" },
        { k: "ค่าไฟเปิด 24 ชม.", v: "~180฿/ด." },
        { k: "เสียง", v: "จานหมุนเบาๆ" },
      ],
      upgrades: [
        { title: "2.5GbE NIC + สวิตช์", cost: "+2,600", gain: "โอนไฟล์เร็วขึ้น 2.5 เท่า (~280MB/s)" },
        { title: "HDD เพิ่ม 2 ลูก", cost: "+10,800", gain: "ขยับเป็น RAID5 ความจุ 24TB" },
        { title: "UPS 850VA", cost: "+2,900", gain: "ZFS เกลียดไฟดับกลางเขียนที่สุด" },
      ],
    },
    {
      id: "h3", min: 35000, max: 300000,
      name: "Proxmox All-in-One — NAS + VM + กล้องวงจรปิด",
      chip: "AIO · VM+NAS",
      watt: 120, idleWatt: 55,
      kase: { name: "Jonsbo N4 (NAS)", w: 286, h: 300 },
      cloud: { rateUsd: 59.94, gpuLabel: "Google One 2TB ×6 (เทียบความจุ 12TB)", refreshMonths: 60, isStorage: true },
      parts: [
        { type: "CPU", name: "Ryzen 7 7700 (8C/65W)", price: 9900, dims: { w: 40, h: 40 },
          reason: "8 คอร์ eco mode — รัน VM 5-6 ตัว + NAS + Frigate ได้ในไฟต่ำ" },
        { type: "MB", name: "B650M (2× NVMe)", price: 4200, dims: { w: 244, h: 244 },
          reason: "NVMe คู่ทำ mirror ให้ VM แยกจากจานข้อมูล" },
        { type: "HDD", name: "HDD NAS 12TB ×2 (RAID1)", price: 15800, dims: { w: 147, h: 52 },
          reason: "เริ่มที่ 12TB คู่ ขยายทีหลังถูกกว่าซื้อเผื่อวันนี้", upgrade: "เพิ่มได้ถึง 6 ลูกในเคสนี้" },
      ],
      parts2: [
        { type: "RAM", name: "DDR5 64GB (2×32)", price: 6900, dims: { w: 134, h: 32 },
          reason: "VM ละ 4-8GB + ZFS cache — 64GB คือเพดานที่สบายไปอีกหลายปี" },
        { type: "SSD", name: "NVMe 1TB ×2 (mirror)", price: 4800, dims: { w: 80, h: 22 },
          reason: "VM อยู่บน mirror — จานเสียหนึ่ง ระบบไม่ล่ม" },
        { type: "PSU", name: "650W 80+ Gold", price: 2600, dims: { w: 150, h: 86 },
          reason: "โหลดจริง ~120W — PSU ทำงานช่วงประสิทธิภาพดีที่สุดพอดี" },
        { type: "CASE", name: "Jonsbo N4 6-Bay", price: 4200, dims: { w: 286, h: 300 },
          reason: "6 ถาดจาน + ช่อง ITX/mATX — โตได้โดยไม่ย้ายบ้าน" },
      ],
      perf: [
        { k: "VM พร้อมกัน", v: "5–8 ตัว" },
        { k: "กล้อง Frigate (ตรวจจับ)", v: "4–6 กล้อง" },
        { k: "Immich + Jellyfin + *arr", v: "ลื่น" },
        { k: "ความจุเริ่มต้น (RAID1)", v: "12TB" },
      ],
      temps: [
        { k: "CPU (eco 65W)", v: "55–65°C" },
        { k: "HDD", v: "38–45°C" },
        { k: "ค่าไฟเปิด 24 ชม.", v: "~390฿/ด." },
      ],
      upgrades: [
        { title: "Google Coral TPU", cost: "+2,500", gain: "Frigate ตรวจจับวัตถุโดยไม่กิน CPU" },
        { title: "10GbE คู่", cost: "+5,500", gain: "ตัดต่อวิดีโอจาก NAS ตรงๆ เหมือนไฟล์ในเครื่อง" },
        { title: "GPU มือสองเล็กๆ", cost: "+4,500", gain: "transcode หนักๆ + ทดลอง LLM เล็ก" },
      ],
    },
  ];

  const GAMING_TIERS = [
    {
      id: "g1", min: 15000, max: 24999,
      name: "1080p Esports — Valorant/Dota ลื่นเกินจอ",
      chip: "1080P ESPORTS",
      watt: 260, idleWatt: 45,
      kase: { name: "mATX Tower", w: 400, h: 425 },
      cloud: { rateUsd: 9.99, gpuLabel: "GeForce NOW Performance", refreshMonths: 36, isGfn: true },
      parts: [
        { type: "GPU", name: "RX 6600 8GB", price: 6200, dims: { w: 220, h: 110 },
          reason: "เฟรมต่อบาทดีสุดของฝั่งล่าง — esports 1080p ทะลุ 200fps ทุกเกม",
          upgrade: "RTX 5060 เมื่ออยากเล่น AAA จริงจัง (+5,300)" },
        { type: "CPU", name: "Intel i5-12400F", price: 3700, dims: { w: 38, h: 38 },
          reason: "6 คอร์ยังพอสำหรับเกมยุคนี้ และถูกกว่า Ryzen ในระดับเดียวกัน" },
        { type: "MB", name: "H610M", price: 2100, dims: { w: 226, h: 180 },
          reason: "ไม่ OC อยู่แล้ว เอาส่วนต่างไปลงการ์ดจอ" },
      ],
      parts2: [
        { type: "RAM", name: "DDR4 16GB (2×8)", price: 1200, dims: { w: 134, h: 32 },
          reason: "คู่แชนแนลสำคัญกว่าความจุในงบนี้", upgrade: "32GB เมื่อเปิดเกม+Discord+Chrome พร้อมกัน" },
        { type: "SSD", name: "NVMe 1TB", price: 1900, dims: { w: 80, h: 22 },
          reason: "เกมเดี๋ยวนี้ 100GB+ — 512GB จะเต็มในเดือนแรก" },
        { type: "PSU", name: "600W 80+ Bronze แบรนด์แท้", price: 1700, dims: { w: 150, h: 86 },
          reason: "PSU โนเนมคือชิ้นเดียวที่พังแล้วลากทั้งเครื่องไปด้วย" },
        { type: "CASE", name: "mATX Airflow", price: 1100, dims: { w: 400, h: 425 },
          reason: "หน้าตะแกรง พัดลมแถม 2 — เย็นกว่าเคสกระจกสวยๆ" },
      ],
      perf: [
        { k: "Valorant 1080p", v: "300+ fps" },
        { k: "Dota 2 / CS2", v: "180–250 fps" },
        { k: "GTA V", v: "~95 fps" },
        { k: "Cyberpunk (Med)", v: "~55 fps" },
      ],
      temps: [
        { k: "GPU", v: "65–72°C" },
        { k: "CPU", v: "55–65°C" },
        { k: "กินไฟตอนเล่น", v: "~260W" },
      ],
      upgrades: [
        { title: "จอ 144Hz", cost: "+3,900", gain: "เครื่องนี้ยิงเฟรมเกิน 60 อยู่แล้ว จออย่าให้เสียของ" },
        { title: "RAM → 32GB", cost: "+1,200", gain: "สลับแอปไม่กระตุก" },
      ],
    },
    {
      id: "g2", min: 25000, max: 39999,
      name: "1080p สูงสุด / ชิม 1440p",
      chip: "1080P ULTRA",
      watt: 330, idleWatt: 50,
      kase: { name: "ATX Mid Tower", w: 445, h: 460 },
      cloud: { rateUsd: 9.99, gpuLabel: "GeForce NOW Performance", refreshMonths: 36, isGfn: true },
      parts: [
        { type: "GPU", name: "RTX 5060 8GB", price: 11500, dims: { w: 242, h: 112 },
          reason: "DLSS 4 ยืดอายุการ์ดได้อีกหลายปี — 1080p Ultra ทุกเกม",
          upgrade: "RTX 5060 Ti 16GB ถ้าเล็ง 1440p ยาวๆ (+5,500)" },
        { type: "CPU", name: "Ryzen 5 7500F", price: 5200, dims: { w: 40, h: 40 },
          reason: "แพลตฟอร์ม AM5 อัปเกรดซีพียูได้ถึง Zen 6 โดยไม่เปลี่ยนบอร์ด" },
        { type: "MB", name: "B650M", price: 3900, dims: { w: 244, h: 244 },
          reason: "ทางอัปเกรดยาวกว่า Intel ในราคาเท่ากัน" },
      ],
      parts2: [
        { type: "RAM", name: "DDR5 32GB (2×16)", price: 3200, dims: { w: 134, h: 32 },
          reason: "เกมใหม่ๆ เริ่มแตะ 16GB แล้ว 32 คือมาตรฐานใหม่" },
        { type: "SSD", name: "NVMe 1TB Gen4", price: 2400, dims: { w: 80, h: 22 },
          reason: "DirectStorage ใช้ประโยชน์จาก Gen4 จริงในเกมใหม่" },
        { type: "PSU", name: "650W 80+ Gold", price: 2300, dims: { w: 150, h: 86 },
          reason: "เผื่ออัปการ์ดจอรุ่นหน้าโดยไม่ต้องเปลี่ยน PSU" },
        { type: "CASE", name: "ATX Airflow", price: 1600, dims: { w: 445, h: 460 },
          reason: "เผื่อการ์ดยาวรุ่นถัดไป" },
      ],
      perf: [
        { k: "AAA 1080p Ultra", v: "90–120 fps" },
        { k: "1440p High + DLSS", v: "~75 fps" },
        { k: "Esports 1080p", v: "250+ fps" },
      ],
      temps: [
        { k: "GPU", v: "62–70°C" },
        { k: "CPU", v: "60–70°C" },
        { k: "กินไฟตอนเล่น", v: "~330W" },
      ],
      upgrades: [
        { title: "จอ 1440p 165Hz", cost: "+6,500", gain: "จุดคุ้มของความคมชัด/ราคา ปี 2026" },
        { title: "SSD เพิ่ม 2TB", cost: "+3,900", gain: "คลังเกมไม่ต้องลบสลับ" },
      ],
    },
    {
      id: "g3", min: 40000, max: 69999,
      name: "1440p High Refresh — จุดหวานของยุคนี้",
      chip: "1440P · 165HZ",
      watt: 420, idleWatt: 55,
      kase: { name: "ATX Mid Tower", w: 465, h: 470 },
      cloud: { rateUsd: 19.99, gpuLabel: "GeForce NOW Ultimate", refreshMonths: 36, isGfn: true },
      parts: [
        { type: "GPU", name: "RTX 5070 12GB", price: 21500, dims: { w: 285, h: 120 },
          reason: "1440p Ultra ทุกเกม + Ray Tracing เปิดได้จริงด้วย DLSS 4",
          upgrade: "RTX 5070 Ti 16GB เพิ่มความชัวร์เรื่อง VRAM (+8,000)" },
        { type: "CPU", name: "Ryzen 7 7800X3D", price: 13900, dims: { w: 40, h: 40 },
          reason: "3D V-Cache คือซีพียูเกมที่แรงสุดต่อบาท เฟรมต่ำสุดนิ่งกว่าใคร" },
        { type: "MB", name: "B650", price: 4900, dims: { w: 305, h: 244 },
          reason: "ATX เต็มตัวเผื่อสล็อตขยาย" },
      ],
      parts2: [
        { type: "RAM", name: "DDR5 32GB 6000CL30", price: 4200, dims: { w: 134, h: 32 },
          reason: "sweet spot ของ Zen 4/5 — ความเร็วนี้ X3D ตอบสนองดีสุด" },
        { type: "SSD", name: "NVMe 2TB Gen4", price: 4500, dims: { w: 80, h: 22 },
          reason: "เกม AAA 3-4 เกมก็ครึ่ง TB แล้ว" },
        { type: "PSU", name: "750W 80+ Gold ATX 3.1", price: 3200, dims: { w: 160, h: 86 },
          reason: "หัว 12V-2x6 native พร้อมสำหรับการ์ดรุ่นถัดไป" },
        { type: "COOL", name: "Tower Cooler คู่พัดลม", price: 1900, dims: { w: 125, h: 158 },
          reason: "7800X3D กินไฟต่ำ ลมแรงๆ เอาอยู่ ไม่ต้อง AIO" },
        { type: "CASE", name: "Mid Tower Airflow", price: 2200, dims: { w: 465, h: 470 },
          reason: "สมดุลเสียง/อุณหภูมิดีสุดในช่วงราคา" },
      ],
      perf: [
        { k: "AAA 1440p Ultra", v: "100–130 fps" },
        { k: "1440p + RT + DLSS", v: "~85 fps" },
        { k: "4K High + DLSS", v: "~60 fps" },
      ],
      temps: [
        { k: "GPU", v: "64–72°C" },
        { k: "CPU (X3D)", v: "70–80°C" },
        { k: "กินไฟตอนเล่น", v: "~420W" },
      ],
      upgrades: [
        { title: "จอ 1440p 240Hz OLED", cost: "+12,000", gain: "อัปเกรดที่รู้สึกได้มากกว่าเปลี่ยนการ์ด" },
        { title: "RTX 5070 Ti", cost: "+8,000", gain: "VRAM 16GB อยู่ยาวถึงเกมปี 2028" },
      ],
    },
    {
      id: "g4", min: 70000, max: 200000,
      name: "4K Ultra — ไม่ต้องประนีประนอม",
      chip: "4K · RT ULTRA",
      watt: 560, idleWatt: 65,
      kase: { name: "Full Tower", w: 520, h: 520 },
      cloud: { rateUsd: 19.99, gpuLabel: "GeForce NOW Ultimate (RTX 4080)", refreshMonths: 36, isGfn: true },
      parts: [
        { type: "GPU", name: "RTX 5080 16GB", price: 42000, dims: { w: 310, h: 137 },
          reason: "4K Ultra 90fps+ ด้วย DLSS 4 — ต่ำกว่านี้ 4K ต้องเริ่มลดกราฟิก",
          upgrade: "RTX 5090 ถ้าอยากได้ 4K 144Hz จริงจัง (+47,000)" },
        { type: "CPU", name: "Ryzen 7 9800X3D", price: 17900, dims: { w: 40, h: 40 },
          reason: "ซีพียูเกมแรงสุดของยุค — ป้อนเฟรมให้การ์ดระดับนี้ทัน" },
        { type: "MB", name: "X870", price: 8900, dims: { w: 305, h: 244 },
          reason: "USB4 + PCIe 5.0 ครบ ไม่ต้องเสียดายทีหลัง" },
      ],
      parts2: [
        { type: "RAM", name: "DDR5 32GB 6000CL30", price: 4200, dims: { w: 134, h: 32 },
          reason: "เกมยังไม่ใช้เกิน 32GB — เก็บเงินไว้อัปจอ", upgrade: "64GB เมื่อตัดต่อ/สตรีมด้วย" },
        { type: "SSD", name: "NVMe 2TB Gen5", price: 6900, dims: { w: 80, h: 22 },
          reason: "โหลดฉากเกม Gen5 เริ่มเห็นผลจริงในเกมปี 2026" },
        { type: "PSU", name: "1000W 80+ Gold ATX 3.1", price: 4900, dims: { w: 180, h: 86 },
          reason: "5080 spike แรง + เผื่ออัป 5090 ได้เลย" },
        { type: "COOL", name: "AIO 360mm", price: 4200, dims: { w: 394, h: 55 },
          reason: "9800X3D บูสต์ค้างได้นานเมื่อเย็น" },
        { type: "CASE", name: "Full Tower เงียบ", price: 3900, dims: { w: 520, h: 520 },
          reason: "ช่องลมใหญ่ = พัดลมหมุนช้า = เงียบทั้งที่แรง" },
      ],
      perf: [
        { k: "4K Ultra + DLSS", v: "90–120 fps" },
        { k: "4K + Path Tracing", v: "~70 fps" },
        { k: "1440p 240Hz", v: "จัดเต็ม" },
      ],
      temps: [
        { k: "GPU", v: "66–74°C" },
        { k: "CPU", v: "68–78°C" },
        { k: "กินไฟตอนเล่น", v: "~560W", hot: true },
      ],
      upgrades: [
        { title: "จอ 4K 144Hz", cost: "+15,000", gain: "ปลดล็อกสิ่งที่เครื่องทำได้จริง" },
        { title: "RTX 5090", cost: "+47,000", gain: "4K ไม่ง้อ DLSS / งาน AI เสริม" },
      ],
    },
  ];

  return {
    FX, ELEC, buyLinks,
    usecases: {
      ai:     { label: "AI Server",   minBuild: 25000, tiers: AI_TIERS },
      home:   { label: "Home Server", minBuild: 5000,  tiers: HOME_TIERS },
      gaming: { label: "เล่นเกม",     minBuild: 15000, tiers: GAMING_TIERS },
    },
  };
})();
